apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx-v1
  name: nginx-replication-controller-v1
spec:
  replicas: 1
  selector:
    name: nginx
    version: v1
  template:
    metadata:
      labels:
        name: nginx
        version: v1
    spec:
      containers:
      - image: kyma/docker-nginx
        name: nginx
        ports:
        - name: nginx
          containerPort: 80
          hostPort: 80
        volumeMounts:
            - name: nginx-website
              mountPath: /var/www
      volumes:
        - name: nginx-website
          hostPath:
            path: /var/www

