apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx-v2
  name: nginx-replication-controller-v2
spec:
  replicas: 1
  selector:
    name: nginx
    version: v2
  template:
    metadata:
      labels:
        name: nginx
        version: v2
    spec:
      containers:
      - image: kyma/docker-nginx
        name: nginx
        ports:
        - name: nginx
          containerPort: 80
          hostPort: 80
        volumeMounts:
            - name: nginx-website
              mountPath: /var/www
      volumes:
        - name: nginx-website
          secret:
            secretName: nginx-website

